apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-api
    namespace: {{namespace}}
spec:
    replicas: 2
    selector:
      matchLabels:
        app: web-api
    strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 50%
          maxUnavailable: 50%
    template:
      metadata:
        labels:
          app: web-api
      spec:
        containers:
          - name: web-api
            image: {{image}}
            imagePullPolicy: "Always"
            ports:
              - containerPort: 8000
            env:
              - name: DB_NAME
                valueFrom:
                  configMapKeyRef:
                    name: web-config
                    key: database_name
              - name: USER_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: web-config
                    key: user_service_host

---
apiVersion: v1
kind: Service
metadata:
    name: web-api
    namespace: {{namespace}}
spec:
    type: LoadBalancer
    ports:
      - targetPort: 8000
        name: apihttp
        port: {{service_port}}
    selector:
      app: web-api
