name: Publish Docker image
on:
  release:
    types: [published]
  pull_request:
    branches: [ "main" ]

jobs:
  build_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.GITUB_PAT }} 
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ghcr.io/alfiandra/${{ github.event.repository.name }}
          
      
      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: ./majelist_service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Latest image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: ./majelist_service
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
          

  update_deployment_staging:
    name: Update staging env
    needs: build_push
    runs-on: ubuntu-latest
    steps:
    - name: Update staging env
      run: echo "update staging"

  update_deployment_production:
    name: Update production env
    if: ${{ github.event.release }}
    needs: build_push
    runs-on: ubuntu-latest
    steps:
    - name: Update production env
      run: echo "update production"
